"""Shared reader for the mobile dependency baseline (M36).

Two things consume this: `verify_platform_foundation.sh` section E2, which
checks the baseline, and `refresh_mobile_dependency_baseline.sh`, which moves
it. They must agree exactly — a validator and a refresh command that parse
`pubspec.yaml` differently would let a bump pass review while failing CI, or
worse, the reverse. One implementation, imported by both.

Deliberately dependency-free. `pubspec.yaml` and `pubspec.lock` are fixed,
simple shapes generated by the Dart toolchain, and this repository has no YAML
library in its Python path; adding one for two files would be a supply-chain
decision taken for the wrong reason.
"""

from __future__ import annotations

import hashlib
import re


def sha256_of(path: str) -> str:
    """Hex sha256 of a file's bytes."""
    with open(path, 'rb') as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def yaml_direct_deps(path: str) -> tuple[dict[str, str], dict[str, str]]:
    """Return (dependencies, dev_dependencies) declared in pubspec.yaml.

    Only top-level, two-space-indented entries are read, which is exactly what
    a direct dependency is. An entry whose value is a nested block (`sdk:`,
    `git:`, `path:`) is recorded as the literal '<nested>' — enough to compare
    the declaration set and to recognise SDK-provided packages, without
    pretending to resolve them.
    """
    deps: dict[str, str] = {}
    dev: dict[str, str] = {}
    section: dict[str, str] | None = None

    for raw in open(path):
        line = raw.rstrip('\n')
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        if re.match(r'^dependencies:\s*$', line):
            section = deps
            continue
        if re.match(r'^dev_dependencies:\s*$', line):
            section = dev
            continue
        if re.match(r'^[A-Za-z_]', line):        # any other top-level key ends the block
            section = None
            continue
        if section is None:
            continue
        m = re.match(r'^  ([A-Za-z0-9_]+):\s*(.*)$', line)
        if m:
            section[m.group(1)] = m.group(2).strip() or '<nested>'

    return deps, dev


def lock_direct_versions(path: str) -> dict[str, str]:
    """Return name -> version for every package pubspec.lock marks as direct.

    Transitive packages are ignored on purpose: they are a consequence of the
    direct set, and pinning them would re-create exactly the brittleness M31's
    hash pin had.
    """
    out: dict[str, str] = {}
    name: str | None = None
    dependency: str | None = None
    version: str | None = None

    def flush() -> None:
        if name and dependency and dependency.startswith('"direct'):
            out[name] = version or ''

    for raw in open(path):
        line = raw.rstrip('\n')
        m = re.match(r'^  ([A-Za-z0-9_]+):\s*$', line)
        if m:
            flush()
            name, dependency, version = m.group(1), None, None
            continue
        m = re.match(r'^    dependency:\s*(.+)$', line)
        if m:
            dependency = m.group(1).strip()
            continue
        m = re.match(r'^    version:\s*"?([^"]+)"?\s*$', line)
        if m:
            version = m.group(1).strip()
    flush()

    return out


def sdk_provided(deps: dict[str, str], dev: dict[str, str]) -> set[str]:
    """Packages declared as a nested block — `flutter`, `flutter_test`, and any
    git/path dependency. These never appear in the lockfile with a resolvable
    version, so they are excluded from the two-way comparison. That is a
    statement about the SDK, not a loophole: an ordinary `name: ^1.2.3` entry is
    never nested and is always compared.
    """
    return {n for n, v in list(deps.items()) + list(dev.items()) if v == '<nested>'}
